name: 'ci'

on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Go test Coverage
        run: go test -coverprofile=coverage.out
